"""empty message

Revision ID: 6641209ecdeb
Revises: 460485c7c9b2
Create Date: 2017-11-16 17:20:22.065543

"""

# revision identifiers, used by Alembic.
revision = '6641209ecdeb'
down_revision = '460485c7c9b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_dates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('to_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('work_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_date',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('from_time', sa.DATETIME(), nullable=False),
    sa.Column('to_time', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('create_date', sa.DATETIME(), nullable=False),
    sa.Column('update_date', sa.DATETIME(), nullable=True),
    sa.Column('delete_date', sa.DATETIME(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('work_dates')
    ### end Alembic commands ###
